In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
import torch

In [5]:
W = torch.arange(12, dtype=torch.float32).reshape(4,3)
W

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [6]:
U, S, V = torch.svd(W)

In [7]:
U

tensor([[-0.0835,  0.8325,  0.5319],
        [-0.3137,  0.4490, -0.8066],
        [-0.5438,  0.0656,  0.0176],
        [-0.7739, -0.3179,  0.2571]])

In [8]:
S

tensor([2.2447e+01, 1.4641e+00, 5.6755e-07])

In [9]:
V

tensor([[-0.4976, -0.7653, -0.4082],
        [-0.5740, -0.0624,  0.8165],
        [-0.6504,  0.6406, -0.4082]])

In [10]:
torch.diag(S)

tensor([[2.2447e+01, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.4641e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 5.6755e-07]])

In [11]:
U @ torch.diag(S) @ V.t()

tensor([[5.5576e-08, 1.0000e+00, 2.0000e+00],
        [3.0000e+00, 4.0000e+00, 5.0000e+00],
        [6.0000e+00, 7.0000e+00, 8.0000e+00],
        [9.0000e+00, 1.0000e+01, 1.1000e+01]])

In [12]:
St = S[:2]
St

tensor([22.4467,  1.4641])

In [13]:
St_diag = torch.diag(St)
St_diag

tensor([[22.4467,  0.0000],
        [ 0.0000,  1.4641]])

In [14]:
import torch.nn.functional as F
St_diag = F.pad(St_diag, (0, 1, 0, 1), mode="constant", value=0)
St_diag

tensor([[22.4467,  0.0000,  0.0000],
        [ 0.0000,  1.4641,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])

In [15]:
U @ St_diag @ V.t()

tensor([[1.7881e-07, 1.0000e+00, 2.0000e+00],
        [3.0000e+00, 4.0000e+00, 5.0000e+00],
        [6.0000e+00, 7.0000e+00, 8.0000e+00],
        [9.0000e+00, 1.0000e+01, 1.1000e+01]])